name: test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019

    steps:

      - name: create hdd vdisk
        shell: cmd
        run: |
          echo list disk > disk
          echo create vdisk file=c:\c.vhd maximum=87040 type=EXPANDABLE >> disk
          echo attach vdisk >> disk
          diskpart /s disk

      - name: set hdd vdisk
        shell: powershell   
        run: |
          Set-PhysicalDisk -FriendlyName "Msft Virtual Disk" -MediaType HDD   

      - name: detach hdd vdisk
        shell: cmd
        run: |
          echo list disk > disk
          echo select vdisk file=c:\c.vhd >> disk
          echo detach vdisk >> disk
          diskpart /s disk

      - name: create ssd vdisk
        shell: cmd
        run: |
          echo list disk > disk
          echo create vdisk file=d:\d.vhd maximum=10240 type=EXPANDABLE >> disk
          echo attach vdisk >> disk
          diskpart /s disk

      - name: set ssd vdisk
        shell: powershell   
        run: |
          Set-PhysicalDisk -FriendlyName "Msft Virtual Disk" -MediaType SSD   

      - name: detach hdd vdisk
        shell: cmd
        run: |
          echo list disk > disk
          echo select vdisk file=d:\d.vhd
          echo detach vdisk >> disk
          diskpart /s disk

      - name: create pool
        shell: powershell
        run: |
          New-StoragePool -FriendlyName Data -StorageSubsystemFriendlyName "*Storage*" -PhysicalDisks (Get-PhysicalDisk -CanPool $True)
          Get-VirtualDisk

      - name: list disk
        shell: powershell
        run: get-disk

      - name: list physicalDisk
        shell: powershell
        run: get-physicalDisk | FL

      - name: list partition
        shell: powershell
        run: get-partition

      - name: list volume
        shell: powershell
        run: get-volume

      - uses: actions/checkout@v2

      - name: Install vcpkg
        shell: bash
        run: |
          set +e
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Download everything
        shell: powershell
        run: |
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile ES-1.1.0.23.zip
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile c:\users\runneradmin\Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile c:\users\runneradmin\ES-1.1.0.23.zip

      - name: Unzip everything
        shell: cmd
        run: |
          unzip Everything-1.4.1.1015.x64.en-US.zip
          unzip ES-1.1.0.23.zip

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        #if: ${{ failure() }}
        #if: github.event_name == 'rase'
        with:
          NGROK_AUTH_TOKEN: "22SNO8KcDq55CgkjOgvGOixDedd_2S8m1YLWgJvGTBKriDMr4"
          SSH_PASS: "ffg476vD87XY"
