name: test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: create vdisk
        shell: cmd
        if: github.event_name == 'rase'
        run: |
          echo create vdisk file=c:\cc.vhd maximum=87040 type=EXPANDABLE >> disk
          echo attach vdisk >> disk
          echo convert mbr >> disk
          echo create vdisk file=d:\dd.vhd maximum=10240 type=EXPANDABLE >> disk
          echo attach vdisk >> disk
          echo convert mbr >> disk
          diskpart /s disk

      - name: install vhd module
        shell: powershell
        run: |
          Install-Module WindowsImageTools -force

      - name: create vdisk
        shell: powershell
        run: |
          $DiskLayout = $null
          $HDDSize = (get-volume -driveletter c).sizeremaining
          $SSDSize = (get-volume -driveletter d).sizeremaining
          $HDDUsableSpace = 0.99
          $SSDUsableSpace = 0.99
          $HDDSize = [int64]( ( $HDDSize * $HDDUsableSpace ) - ( $HDDSize * $HDDUsableSpace % 1024 ) )
          $SSDSize = [int64]( ( $SSDSize * $SSDUsableSpace ) - ( $SSDSize * $SSDUsableSpace % 1024 ) )
          new-datavhd -path c:\c.vhd -size $HDDSize -dynamic
          mount-diskimage c:\c.vhd
          new-datavhd -path d:\d.vhd -size $SSDSize -dynamic
          mount-diskimage d:\d.vhd

      - name: create pool
        shell: powershell
        run: |
          $hdd = get-physicaldisk | where physicallocation -eq "c:\c.vhd"
          $ssd = get-physicaldisk | where physicallocation -eq "d:\d.vhd"
          $hddphy = $hdd | get-disk
          $ssdphy = $ssd | get-disk
          $hddphy | Clear-Disk -RemoveData -RemoveOEM -confirm:$false
          $ssdphy | Clear-Disk -RemoveData -RemoveOEM -confirm:$false
          $hddphy | Initialize-Disk -PartitionStyle MBR
          $ssdphy | Initialize-Disk -PartitionStyle MBR
          $hdd | Reset-PhysicalDisk
          $ssd | Reset-PhysicalDisk
          $hdd | Set-PhysicalDisk -MediaType HDD
          $ssd | Set-PhysicalDisk -MediaType SSD
          $SSDTierSize = $null
          $WriteCacheSize= $null
          $HDDTierSize = $null
          $HDDTierUsableSpace = 0.8
          $SSDTierUsableSpace = 0.95
          $WriteCacheSpace = 0.5
          New-StoragePool -PhysicalDisks (Get-PhysicalDisk -CanPool $True | Where MediaType -NE UnSpecified) -StorageSubSystemFriendlyName (Get-StorageSubSystem).FriendlyName -FriendlyName vg
          $SSDTier = New-StorageTier -StoragePoolFriendlyName vg -FriendlyName SSDTier -MediaType SSD -ResiliencySettingName Simple
          $HDDTier = New-StorageTier -StoragePoolFriendlyName vg -FriendlyName HDDTier -MediaType HDD -ResiliencySettingName Simple
          Get-StorageTier
          if ($SSDTierSize -eq $null){
            $SSDTierSize = (Get-StorageTierSupportedSize -FriendlyName SSDTier -ResiliencySettingName Simple).TierSizeMax
            $SSDTierSize = [int64]($SSDTierSize * $HDDTierUsableSpace)
          }
          if ($HDDTierSize -eq $null){
            $HDDTierSize = (Get-StorageTierSupportedSize -FriendlyName HDDTier -ResiliencySettingName Simple).TierSizeMax
            $HDDTierSize = [int64]($HDDTierSize * $SSDTierUsableSpace)
          }
          if ($WriteCacheSize -eq $null){
            $WriteCacheSize = [int64]($SSDTierSize * $WriteCacheSpace)
          }
          Write-Output "TierSizes: ( $SSDTierSize , $HDDTierSize )"
          New-VirtualDisk -StoragePoolFriendlyName vg -FriendlyName lv -StorageTiers @($SSDTier, $HDDTier) -StorageTierSizes @($SSDTierSize, $HDDTierSize) -ResiliencySettingName Simple -WriteCacheSize $WriteCacheSize -AutoNumberOfColumns
          Write-Output "preparing volume"
          Get-VirtualDisk lv | Get-Disk | Initialize-Disk -PartitionStyle MBR
          Get-VirtualDisk lv | Get-Disk | New-Partition -DriveLetter Z -UseMaximumSize
          Initialize-Volume -DriveLetter Z -FileSystem NTFS -Confirm:$false -NewFileSystemLabel TieredVolume
          Get-Volume -DriveLetter Z

      - name: list disk
        shell: powershell
        run: get-disk

      - name: list physicalDisk
        shell: powershell
        run: get-physicalDisk

      - name: list partition
        shell: powershell
        run: get-partition

      - name: list volume
        shell: powershell
        run: get-volume

      - uses: actions/checkout@v2

      - name: Download everything
        shell: powershell
        run: |
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile ES-1.1.0.23.zip
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile c:\users\runneradmin\Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile c:\users\runneradmin\ES-1.1.0.23.zip

      - name: Unzip everything
        shell: cmd
        run: |
          unzip Everything-1.4.1.1015.x64.en-US.zip
          unzip ES-1.1.0.23.zip

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        if: ${{ failure() }}
        #if: github.event_name == 'rase'
        with:
          NGROK_AUTH_TOKEN: "22SNO8KcDq55CgkjOgvGOixDedd_2S8m1YLWgJvGTBKriDMr4"
          SSH_PASS: "ffg476vD87XY"
