name: test

on:

  push:
    branches: master
      
jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2    
    - name: Install vcpkg
      shell: bash
      run: |
        set +e
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.sh
    
    - name: Download everything
      shell: powershell
      run: |
        wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile Everything-1.4.1.1015.x64.en-US.zip
        wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile ES-1.1.0.23.zip
        wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile c:\users\runneradmin\Everything-1.4.1.1015.x64.en-US.zip
        wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile c:\users\runneradmin\ES-1.1.0.23.zip

    - name: Unzip everything
      shell: cmd
      run: |
        unzip Everything-1.4.1.1015.x64.en-US.zip
        unzip ES-1.1.0.23.zip
        
    - name: create vdisk
      shell: cmd
      run: |
        echo
        
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: "22SNO8KcDq55CgkjOgvGOixDedd_2S8m1YLWgJvGTBKriDMr4"
        SSH_PASS: "ffg476vD87XY" 
