name: test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: install vhd module
        shell: powershell
        run: |
          Install-Module WindowsImageTools -force

      - name: create vdisk
        shell: powershell
        run: |
          $DiskLayout = $null
          $HDDSize = (get-volume -driveletter c).sizeremaining
          $SSDSize = (get-volume -driveletter d).sizeremaining
          $HDDUsableSpace = 0.98
          $SSDUsableSpace = 0.98
          $HDDSize = [int64]( ( $HDDSize * $HDDUsableSpace ) - ( $HDDSize * $HDDUsableSpace % 1024 ) )
          $SSDSize = [int64]( ( $SSDSize * $SSDUsableSpace ) - ( $SSDSize * $SSDUsableSpace % 1024 ) )
          new-datavhd -path c:\c.vhd -size $HDDSize -dynamic
          mount-diskimage c:\c.vhd
          new-datavhd -path d:\d.vhd -size $SSDSize -dynamic
          mount-diskimage d:\d.vhd

      - name: create pool
        shell: powershell
        run: |
          $ReseverSpace = 5324351488
          $WriteCacheSpace = 0.5
          $SSDTierSpace = 0.95
          $HDDTierSpace = 0.9
          $hdd = get-physicaldisk | where physicallocation -eq "c:\c.vhd"
          $ssd = get-physicaldisk | where physicallocation -eq "d:\d.vhd"
          $hddphy = $hdd | get-disk
          $ssdphy = $ssd | get-disk
          $hddphy | get-disk | where partitionstyle -ne raw | clear-disk -RemoveData -confirm:$false
          $ssdphy | get-disk | where partitionstyle -ne raw | clear-disk -RemoveData -confirm:$false
          #$hddphy | get-disk | where partitionstyle -eq raw | Initialize-Disk -PartitionStyle MBR
          #$ssdphy | get-disk | where partitionstyle -eq raw | Initialize-Disk -PartitionStyle MBR
          $hdd | Reset-PhysicalDisk
          $ssd | Reset-PhysicalDisk
          $hdd | Set-PhysicalDisk -MediaType HDD
          $ssd | Set-PhysicalDisk -MediaType SSD
          New-StoragePool -PhysicalDisks (Get-PhysicalDisk -CanPool $True | Where MediaType -NE UnSpecified) -StorageSubSystemFriendlyName (Get-StorageSubSystem).FriendlyName -FriendlyName vg
          $SSDTier = New-StorageTier -StoragePoolFriendlyName vg -FriendlyName SSDTier -MediaType SSD -ResiliencySettingName Simple
          $HDDTier = New-StorageTier -StoragePoolFriendlyName vg -FriendlyName HDDTier -MediaType HDD -ResiliencySettingName Simple
          $SSDTierSize = (Get-StorageTierSupportedSize -FriendlyName SSDTier -ResiliencySettingName Simple).TierSizeMax
          $SSDTierSize = [int64]($SSDTierSize * $SSDTierSpace)
          $HDDTierSize = (Get-StorageTierSupportedSize -FriendlyName HDDTier -ResiliencySettingName Simple).TierSizeMax
          $HDDTierSize = [int64]($HDDTierSize * $HDDTierSpace)
          $WriteCacheSize = [int64]($SSDTierSize * $WriteCacheSpace)
          Write-Output "TierSizes: ( $SSDTierSize , $HDDTierSize )"
          New-VirtualDisk -StoragePoolFriendlyName vg -FriendlyName lv -StorageTiers @($SSDTier, $HDDTier) -StorageTierSizes @($SSDTierSize, $HDDTierSize) -ResiliencySettingName Simple
          #-WriteCacheSize $WriteCacheSize
          $SSDRemain = [int64]( ($ssd | get-physicaldisk | select size).size - ($ssd | get-physicaldisk | select allocatedsize).allocatedsize)
          $HDDRemain = [int64]( ($hdd | get-physicaldisk | select size).size - ($hdd | get-physicaldisk | select allocatedsize).allocatedsize)
          write-output "SSDRemain: $SSDRemain"
          write-output "HDDRemain: $HDDRemain"
          Get-VirtualDisk lv | Get-Disk | Initialize-Disk -PartitionStyle MBR
          Get-VirtualDisk lv | Get-Disk | New-Partition -DriveLetter Z -UseMaximumSize
          Initialize-Volume -DriveLetter Z -FileSystem NTFS -Confirm:$false -NewFileSystemLabel TieredVolume
          Get-Volume -DriveLetter Z

      - name: list disk
        shell: powershell
        run: get-disk

      - name: list physicalDisk
        shell: powershell
        run: get-physicalDisk

      - name: list partition
        shell: powershell
        run: get-partition

      - name: list volume
        shell: powershell
        run: get-volume

      - uses: actions/checkout@v2

      - name: Download everything
        shell: powershell
        run: |
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile ES-1.1.0.23.zip
          wget https://www.voidtools.com/Everything-1.4.1.1015.x64.en-US.zip -outfile c:\users\runneradmin\Everything-1.4.1.1015.x64.en-US.zip
          wget https://www.voidtools.com/ES-1.1.0.23.zip -outfile c:\users\runneradmin\ES-1.1.0.23.zip

      - name: Unzip everything
        shell: cmd
        run: |
          unzip Everything-1.4.1.1015.x64.en-US.zip
          unzip ES-1.1.0.23.zip

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        #if: ${{ failure() }}
        #if: github.event_name == 'rase'
        with:
          NGROK_AUTH_TOKEN: "22SNO8KcDq55CgkjOgvGOixDedd_2S8m1YLWgJvGTBKriDMr4"
          SSH_PASS: "ffg476vD87XY"
