name: test

on:

  push:
    branches: master
      
jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2    
    - name: Install vcpkg
      shell: bash
      run: |
        set +e
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: "22SNO8KcDq55CgkjOgvGOixDedd_2S8m1YLWgJvGTBKriDMr4"
        SSH_PASS: "ffg476vD87XY" 

